export { 
    KeyNames 
}
export type {
    KeyName
}

type KeyName = typeof KeyNames[keyof typeof KeyNames]

const KeyNames = {
    "": "" , 
    a : "a",
    b : "b",
    c : "c",
    d : "d",
    e : "e",
    f : "f",
    g : "g",
    h : "h",
    i : "i",
    j : "j",
    k : "k",
    l : "l",
    m : "m",
    n : "n",
    o : "o",
    p : "p",
    q : "q",
    r : "r",
    s : "s",
    t : "t",
    u : "u",
    v : "v",
    w : "w",
    x : "x",
    y : "y",
    z : "z",
    A: "A",
    B: "B",
    C: "C",
    D: "D",
    E: "E",
    F: "F",
    G: "G",
    H: "H",
    I: "I",
    J: "J",
    K: "K",
    L: "L",
    M: "M",
    N: "N",
    O: "O",
    P: "P",
    Q: "Q",
    R: "R",
    S: "S",
    T: "T",
    U: "U",
    V: "V",
    W: "W",
    X: "X",
    Y: "Y",
    Z: "Z",
    Control     : "Control",
    Shift       : "Shift",
    Alt         : "Alt",
    Meta        : "Meta",
    Space       : "Space",
    Backspace   : "Backspace",
    Enter       : "Enter",
    Tab         : "Tab",
    Escape      : "Escape",
    Delete      : "Delete",
    ArrowUp     : "ArrowUp",
    ArrowDown   : "ArrowDown",
    ArrowLeft   : "ArrowLeft",
    ArrowRight  : "ArrowRight",

    " ": "Space" , 
    "ctrl": "Control",
    "shift": "Shift",
    "alt": "Alt",
    "meta": "Meta",
    "backspace": "Backspace",
    "enter": "Enter",
    "tab": "Tab",
    "escape": "Escape",
    "delete": "Delete",
    "arrowup": "ArrowUp",
    "arrowdown": "ArrowDown",
    "arrowleft": "ArrowLeft",
    "arrowright": "ArrowRight",
    
} as const

